[package]
name = "plugin-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
opt_args = "2.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
strum_macros = "0.27.1"
